---
- hosts: demo
  become: yes
  tasks:
     - name: wait for  service to start listening on port 80
       wait_for:
         port: 80
         state: started
     - name: wait until file to be  presnt here n the path
       wait_for:
         path: /tmp/dummy
         delay: 5
         timeout: 10
     - name: Eot
       command: echo eot    
          

